### ISSUE TITLE
[PATCH] Fix up bug User-Agent variable usage

### ISSUE THREAD

**Issue by de4ault** [51Degrees/device-detection-nginx#2] opened 2021-07-27 10:21 UTC
This patch fix some issues:
Installing a handler at the rewrite phase leads to inoperability together with the rewrite and lua-openresty modules, since in the case of the first defined worker process, control may not reach 51degrees handler at all, in the case of the second one it is forced to be executed by the last one in the chain of handlers(always after 51degrees) 

User-Agent usage code from an arbitrary variable has the bug in the code, which lead to the overwriting of the variable and the impossibility of its subsequent search. the volume for allocating variable memory was calculated incorrectly. 

The config merge code does not scale well with main/server/location configurations at once, which lead to 100% cpu load, starting with 8krps per nginx worker process
Patch fix - [51degrees.zip](https://github.com/51Degrees/device-detection-nginx/files/6884683/51degrees.zip)

**Comment by de4ault** [comment] 2021-07-27 10:28
patch fix - 
[51degrees.zip](https://github.com/51Degrees/device-detection-nginx/files/6884676/51degrees.zip)

**Comment by tungntpham** [comment] 2021-08-05 11:28
Hi @de4ault ,

Many thanks for your patience and the patch fix. We will review the changes and have you updated as soon as we can.

Kind Regards,

**Comment by tungntpham** [comment] 2022-02-16 08:46
Hi @de4ault,

After much thought on your proposed changes, we have concluded that it is not possible for us to integrate the changes at this point due to the followings:
1.	The reason for a handle to be registered at rewrite phase is to allow detections to be performed before the requests are redirected to other server in the case where Nginx server acts as a reversed proxy.
2.	By design, we wanted to allow configuration of the detection module to be done at different levels (i.e. http, server, location). Each sub block will inherit the settings from its parent. Settings made in the sub block will overwrite one that was set in their parent. The provided patch broke this feature.
a.	Having said that, we certainly will look to allocate some time to look at the performance factor that you have raised.

Apart from the above, we have fixed the bug on the arbitrary variables as detailed [here](https://github.com/51Degrees/device-detection-nginx/issues/3).

I will close this for now. Please contact our support if you would like to discuss this further.

Kind Regards,
Tung.

**Closed by tungntpham** 2022-02-16 08:46 UTC
Labels: status: to be scheduled
